export default {
  COIN_LISTINGS_LOAD_REQUEST: '@@COIN_LISTINGS/LOAD/REQUEST',
  COIN_LISTINGS_LOAD_SUCCESS: '@@COIN_LISTINGS/LOAD/SUCCESS',
  COIN_LISTINGS_LOAD_FAILURE: '@@COIN_LISTINGS/LOAD/FAILURE',
}
